# Documentation configuration for libretranslate-mobile.

INHERIT: .mkdocs-shared/shared/mkdocs.base.yml

site_name: 'LibreTranslate Mobile'
site_description: 'Documentation for LibreTranslate Mobile.'
site_author: willtheorangeguy
site_url: https://williamvdg.me/libretranslate-mobile/

repo_url: https://github.com/willtheorangeguy/libretranslate-mobile
repo_name: willtheorangeguy/libretranslate-mobile
edit_uri: edit/main/docs/

copyright: Copyright &copy; willtheorangeguy

nav:
  - Home: index.md
  - 'Quickstart': 'quickstart.md'
  - 'Installation': 'installation.md'
  - 'Configuration': 'configuration.md'
  - 'Architecture': 'architecture.md'
  - 'API': 'api.md'
  - 'Development': 'development.md'
  - 'FAQ': 'faq.md'
  - 'Troubleshooting': 'troubleshooting.md'
  - 'Roadmap': 'roadmap.md'
  - 'App Store Metadata Draft': 'app-store/metadata.md'
  - 'Release Notes': 'app-store/release-notes.md'
  - 'libretranslate-mobile': 'internal/known-issues.md'
  - Changelog: changelog.md
  - License: license.md
  - Contributing: https://github.com/willtheorangeguy/.github/blob/main/CONTRIBUTING.md
  - Code of Conduct: https://github.com/willtheorangeguy/.github/blob/main/CODE_OF_CONDUCT.md
  - Security: https://github.com/willtheorangeguy/.github/blob/main/SECURITY.md

exclude_docs: |
  docs.instructions.md